// nss-vit-nuxt/pages/events.vue
<script setup lang="ts">
const { data: sliderData } = await useAsyncData('events-slider', () =>
  queryContent('/events/slider-data').findOne()
);

const { data: accordionData } = await useAsyncData('events-accordion', () =>
  queryContent('/events/accordion-data').findOne()
);

useHead({
  title: sliderData.value?.pageTitle || 'NSS VIT | Events',
  meta: [
    { name: 'description', content: sliderData.value?.description || 'Explore the diverse events organized by NSS VIT' },
    { property: 'og:title', content: sliderData.value?.pageTitle || 'NSS VIT | Events' },
    { property: 'og:description', content: sliderData.value?.description || 'Explore the diverse events organized by NSS VIT' },
    { property: 'og:url', content: 'https://www.nssvit.in/events' },
    { property: 'og:image', content: sliderData.value?.ogImage || 'https://res.cloudinary.com/du6zyqqyw/image/upload/v1740557668/img/nss-logo.png' },
    { name: 'twitter:title', content: sliderData.value?.pageTitle || 'NSS VIT | Events' },
    { name: 'twitter:description', content: sliderData.value?.description || 'Explore the diverse events organized by NSS VIT' },
    { name: 'twitter:image', content: sliderData.value?.twitterImage || 'https://res.cloudinary.com/du6zyqqyw/image/upload/v1740557668/img/nss-logo.png' },
  ],
});
</script>

<template>
  <div v-if="sliderData && accordionData">
    <EventsSlider :testimonials="sliderData.slides" />
    <EventsAccordion :accordionItems="accordionData.accordionItems" />
  </div>
  <div v-else class="min-h-screen flex items-center justify-center">
    <p>Loading events information...</p>
  </div>
</template>

// nss-vit/src/components/Events.jsx
import React from 'react'
import { Helmet, HelmetProvider } from 'react-helmet-async'
import Slider from './events/Slider'
import Accordian from './events/Accordian'

const Events = () => {
  return (
    <HelmetProvider>
      <div>
        <Helmet>
          <title>NSS VIT | Events</title>

          <meta name="description" content="Explore the diverse events organized by NSS VIT, including workshops, seminars, and community outreach programs aimed at making a positive impact." />

          {/* Open Graph Meta Tags */}
          <meta property="og:title" content="NSS VIT | Events" />
          <meta property="og:description" content="Explore the diverse events organized by NSS VIT, including workshops, seminars, and community outreach programs aimed at making a positive impact." />
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://www.nssvit.in/events" />
          <meta property="og:image" content="https://res.cloudinary.com/du6zyqqyw/image/upload/v1740557668/img/nss-logo.png" />

          {/* Twitter Meta Tags */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta property="twitter:domain" content="nssvit.in" />
          <meta property="twitter:url" content="https://www.nssvit.in/events" />
          <meta name="twitter:title" content="NSS VIT | Events" />
          <meta name="twitter:description" content="Explore the diverse events organized by NSS VIT, including workshops, seminars, and community outreach programs aimed at making a positive impact." />
          <meta name="twitter:image" content="https://res.cloudinary.com/du6zyqqyw/image/upload/v1740557668/img/nss-logo.png" />

        </Helmet>
        <Slider />
        <Accordian />
      </div>
    </HelmetProvider>
  )
}

export default Events
