// nss-vit-nuxt/pages/team.vue
<script setup lang="ts">
const { data: profilesData } = await useAsyncData('team-profiles', () =>
  queryContent('/team/profiles').findOne()
);

const { data: volunteersData } = await useAsyncData('team-volunteers', () =>
  queryContent('/team/volunteers').findOne()
);

useHead({
  title: profilesData.value?.pageTitle || 'NSS VIT | Team',
  meta: [
    { name: 'description', content: profilesData.value?.description || 'Discover our NSS VIT Team, dedicated to fostering community service and personal growth among students' },
    { property: 'og:title', content: profilesData.value?.pageTitle || 'NSS VIT | Team' },
    { property: 'og:description', content: profilesData.value?.description || 'Discover our NSS VIT Team, dedicated to fostering community service and personal growth among students' },
    { property: 'og:url', content: 'https://www.nssvit.in/team' },
    { property: 'og:image', content: profilesData.value?.ogImage || 'https://res.cloudinary.com/du6zyqqyw/image/upload/v1740557668/img/nss-logo.png' },
    { name: 'twitter:title', content: profilesData.value?.pageTitle || 'NSS VIT | Team' },
    { name: 'twitter:description', content: profilesData.value?.description || 'Discover our NSS VIT Team, dedicated to fostering community service and personal growth among students' },
    { name: 'twitter:image', content: profilesData.value?.twitterImage || 'https://res.cloudinary.com/du6zyqqyw/image/upload/v1740557668/img/nss-logo.png' },
  ],
});
</script>

<template>
  <div v-if="profilesData && volunteersData" class="bg-background min-h-screen">
    <div class="container mx-auto px-4 py-8">
      <h1 class="text-4xl md:text-5xl font-bold text-center my-8 animate-fade-in text-transparent bg-clip-text bg-gradient-primary">
        {{ profilesData.headerTitle }}
      </h1>
      <div class="max-w-7xl mx-auto">
        <TeamProfiles 
          :profiles="profilesData.profiles" 
          :defaultFallbackImg="profilesData.defaultFallbackImg" 
        />
        <TeamVolunteers 
          :volunteerData="volunteersData.volunteerData" 
        />
      </div>
    </div>
  </div>
  <div v-else class="min-h-screen flex items-center justify-center">
    <p>Loading team information...</p>
  </div>
</template>

// nss-vit/src/components/Team.jsx
import React from 'react'
import Profiles from './team/Profiles'
import Volunteers from './team/Volunteers'
import { Helmet, HelmetProvider } from 'react-helmet-async'

const Team = () => {
  return (
    <HelmetProvider>
      <div className="bg-background min-h-screen">
        <Helmet>
          <title>NSS VIT | Team</title>
          <meta name="description" content="Discover our NSS VIT Team, dedicated to fostering community service and personal growth among students through various social initiatives." />
          
          {/* Open Graph Meta Tags */}
          <meta property="og:title" content="NSS VIT | Team" />
          <meta property="og:description" content="Discover our NSS VIT Unit, dedicated to fostering community service and personal growth among students through various social initiatives." />
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://www.nssvit.in/team" />
          <meta property="og:image" content="https://res.cloudinary.com/du6zyqqyw/image/upload/v1740557668/img/nss-logo.png" />

          {/* Twitter Meta Tags */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta property="twitter:domain" content="nssvit.in" />
          <meta property="twitter:url" content="https://www.nssvit.in/team" />
          <meta name="twitter:title" content="NSS VIT | Team" />
          <meta name="twitter:description" content="Discover our NSS VIT Unit, dedicated to fostering community service and personal growth among students through various social initiatives." />
          <meta name="twitter:image" content="https://res.cloudinary.com/du6zyqqyw/image/upload/v1740557668/img/nss-logo.png" />
        </Helmet>
        
        <div className="container mx-auto px-4 py-8">
          <h1 className="text-4xl md:text-5xl font-bold text-center my-8 animate-fade-in text-transparent bg-clip-text bg-gradient-primary">
            Our Team
          </h1>
          <div className="max-w-7xl mx-auto">
            <Profiles />
            <Volunteers />
          </div>
        </div>
      </div>
    </HelmetProvider>
  )
}

export default Team
