// nss-vit/src/components/home/Announcements.tsx
/**
 * ╻ NSS-VIT
 * ┃ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * ┃ Not Me, But You
 * ┃
 * ┃ Announcements.tsx
 * ╹ src/components/home/
 */

import { motion } from 'framer-motion';

interface Announcement {
  title: string;
  description: string;
  date: string;
  type: 'info' | 'achievement' | 'event';
  image?: string;
  link?: string;
}

interface Props {
  items?: Announcement[];
}

const defaultAnnouncements: Announcement[] = [
  {
    date: '24-02-2025',
    title: 'NSS Scrutiny Announcement',
    description: 'Our NSS unit is scheduled for scrutiny on 27th February 2025 at Lala Lajpatrai College.',
    type: 'info',
  },
  {
    date: '15-02-2025',
    title: 'Competition Achievements',
    description: 'Our volunteers secured multiple wins in inter-college competitions across Mumbai.',
    type: 'achievement',
    link: '/achievements',
  },
  {
    date: '04-12-2024',
    title: 'Special Camp 2024-2025 Success',
    description: 'The NSS Special Camp to Kuderan Village was a huge success with great community engagement.',
    type: 'event',
  },
  {
    date: '26-11-2024',
    title: 'Quiz & Debate Competition Wins',
    description: 'Our volunteers won 1st place in both Quiz and Debate competitions on Road Safety Awareness.',
    type: 'achievement',
  },
];

const typeStyles = {
  info: 'border-l-primary',
  achievement: 'border-l-status-success',
  event: 'border-l-status-warning',
};

export default function Announcements({ items }: Props) {
  const announcements = items || defaultAnnouncements;
  return (
    <div className="space-y-4">
      {announcements.map((announcement, index) => (
        <motion.div
          key={index}
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ delay: index * 0.1 }}
          className={`border border-swiss-gray-200 border-l-4 ${typeStyles[announcement.type as keyof typeof typeStyles]} p-6 hover:border-swiss-gray-300 transition-colors`}
        >
          <div className="flex flex-col md:flex-row md:items-start gap-3 md:gap-4">
            {announcement.image && (
              <div className="w-full md:w-48 h-32 flex-shrink-0 overflow-hidden">
                <img
                  src={announcement.image}
                  alt={announcement.title}
                  className="w-full h-full object-cover md:grayscale md:hover:grayscale-0 transition-all duration-500"
                />
              </div>
            )}
            <div className="flex-1">
              <div className="flex items-center gap-2 md:gap-3 mb-2">
                <span className="text-label text-swiss-gray-400">{announcement.date}</span>
                <span className="text-label text-primary uppercase">
                  {announcement.type === 'achievement' && 'Achievement'}
                  {announcement.type === 'info' && 'Announcement'}
                  {announcement.type === 'event' && 'Event'}
                </span>
              </div>
              <h4 className="text-caption md:text-title font-semibold text-text mb-2">{announcement.title}</h4>
              <p className="text-caption md:text-body text-swiss-gray-600">{announcement.description}</p>
              {announcement.link && (
                <a
                  href={announcement.link}
                  className="inline-flex items-center gap-2 text-caption text-primary mt-3 hover:underline"
                >
                  View Details
                  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M5 12h14"/>
                    <path d="m12 5 7 7-7 7"/>
                  </svg>
                </a>
              )}
            </div>
          </div>
        </motion.div>
      ))}
    </div>
  );
}

// nss-vit-nuxt/components/home/Announcements.vue
<script setup lang="ts">
const { data: announcementsData } = await useAsyncData('home-announcements', () => queryContent('/home/announcements').findOne())
</script>

<template>
  <div v-if="announcementsData" class="py-12 px-6 sm:px-10 lg:px-16 bg-background animate-fade-in">
    <div class="max-w-6xl mx-auto">
      <h2 class="text-4xl font-bold text-center text-transparent bg-clip-text bg-gradient-primary mb-12">
        {{ announcementsData.title || 'Latest Announcements' }}
      </h2>
      
      <div v-if="announcementsData.announcements" class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div v-for="(announcement, index) in announcementsData.announcements" :key="index" 
          class="p-6 bg-gradient-card rounded-xl shadow-soft hover:shadow-lg transition-all duration-300 flex flex-col">
          
          <div class="flex justify-between items-start mb-4">
            <h3 class="text-xl font-semibold text-primary">{{ announcement.title }}</h3>
            <span class="text-sm text-text/60 bg-primary/10 px-2 py-1 rounded">{{ announcement.date }}</span>
          </div>
          
          <p class="text-text/80 mb-4">{{ announcement.intro }}</p>
          
          <!-- Conditionally render images if available -->
          <div v-if="announcement.images && announcement.images.length" class="mb-4 grid grid-cols-3 gap-2">
            <div v-for="(img, imgIndex) in announcement.images.slice(0, 3)" :key="imgIndex" class="aspect-square overflow-hidden rounded-lg">
              <img :src="img" :alt="`Announcement image ${imgIndex + 1}`" class="w-full h-full object-cover hover:scale-105 transition-transform duration-300" />
            </div>
          </div>
          
          <!-- Single image if provided -->
          <div v-if="announcement.image" class="mb-4 w-full">
            <img :src="announcement.image" :alt="announcement.title" class="w-full h-48 object-cover rounded-lg" />
          </div>
          
          <p v-if="announcement.body" class="text-text/70 mb-4">{{ announcement.body }}</p>
          
          <!-- Optional link -->
          <div v-if="announcement.link" class="mt-auto pt-4">
            <NuxtLink :to="announcement.link.url" class="inline-flex items-center text-primary hover:text-primary-dark">
              {{ announcement.link.text }}
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 ml-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
              </svg>
            </NuxtLink>
          </div>
        </div>
      </div>
      
      <!-- Fallback for when there are no announcements -->
      <div v-else class="h-64 bg-gray-100 animate-pulse rounded-xl"></div>
    </div>
  </div>
</template>
